Task/rewording
dataiku/mealy pull request #12
Opened 2021-03-18 15:01 UTC by simonamaggio

- global error to total error fraction

2021-03-18 18:03 UTC, AgatheG commented
Do we want Error tree or Error analyzer tree?

2021-03-22 15:59 UTC, AgatheG requested changes
There are several instances of `Model Performance Predictor` left:
- README.md: l.71, 75, 78, 131, 135, 138
- error_analyzer.py: l.193
- error_visualizer.py: l.77, 105, 209

2021-03-22 15:59 UTC, AgatheG commented on README.md
> +print(error_analyzer.evaluate(X_test, y_test, output_format='text'))
You should change `evaluate` to return the string (for now it prints it).
Also nitpick, we do not need not have `output_format='text'` as it is the default (same on l.136)

2021-03-22 15:59 UTC, AgatheG commented on README.md
>  # plot the Model Performance Predictor Decision Tree
```suggestion
# plot the Error Tree
```

2021-03-22 15:59 UTC, AgatheG commented on README.md
>  # plot the Model Performance Predictor Decision Tree
```suggestion
# plot the Error Tree
```

2021-03-22 15:59 UTC, AgatheG commented on examples/plot_mealy.py
> +# Plot the Error Decision Tree.
[Extreme nitpick]
Can be simply `Error Tree` as we use this term everywhere else? Not very important, for consistency

2021-03-22 15:59 UTC, AgatheG commented on examples/plot_mealy_pipeline.py
> +# Plot the Error Decision Tree.
Same comment here

2021-03-22 15:59 UTC, AgatheG commented on examples/plot_mealy_pipeline.py
> +# Let's focus on the nodes of the Error Decision Tree, in particular the leaf nodes
Likewise

2021-03-22 15:59 UTC, AgatheG commented on mealy/error_tree.py
> +        self._total_error_fraction = wrongly_predicted_samples.astype(float) / n_total_errors
Easier to cast one iinteger to float than a whole array
```suggestion
        self._total_error_fraction = wrongly_predicted_samples / float(n_total_errors)

```

2021-03-22 15:59 UTC, AgatheG commented on mealy/error_tree.py
>          n_total_errors = np.sum(wrongly_predicted_samples) #y[y == ErrorAnalyzerConstants.WRONG_PREDICTION].shape[0]
```suggestion
        n_total_errors = np.sum(wrongly_predicted_samples)
```

2021-03-22 15:59 UTC, AgatheG commented on mealy/tests/test_error_analyzer.py
>          'primary_model_predicted_accuracy': 1, #0.9011208352525718,
```suggestion
        'primary_model_predicted_accuracy': 1,
```

2021-03-22 17:58 UTC, AgatheG commented on mealy/error_tree.py
> +        self._total_error_fraction = wrongly_predicted_samples.astype(float) / n_total_errors
Easier to cast one iinteger to float than a whole array
```suggestion
        self._total_error_fraction = wrongly_predicted_samples / float(n_total_errors)

```

2021-03-23 14:35 UTC, AgatheG approved these changes
:+1:

2021-03-23 14:49 UTC, du-phan approved these changes

2021-03-23 14:53 UTC, merged