Hotfix/histogram duplicates or absent
dataiku/mealy pull request #7
Opened 2021-02-03 11:00 UTC by simonamaggio

- when user selected `top_k_features` to display all feature distributions, some of them were not shown as they have 0 importance for the decision tree, but the user needs to be able to look at the distribution of all features in a node
- when using pipeline, some features hist were duplicated (multiple hist for the one hot encoded features)

2021-02-19 15:59 UTC, AgatheG requested changes
Are the duplicates really duplicates? Is it not that for one hot encoded categorical features, you get a distribution for each category?

2021-02-19 15:59 UTC, AgatheG commented on mealy/error_visualizer.py
> +                                  ranked_feature_ids]))
```suggestion
            ranked_feature_ids = list(set(self.pipeline_preprocessor.inverse_transform_feature_id(idx) for idx in
                                  ranked_feature_ids))
```

2021-02-22 10:20 UTC, simonamaggio commented
> Are the duplicates really duplicates? Is it not that for one hot encoded categorical features, you get a distribution for each category?

yes, exactly

2021-02-22 10:32 UTC, simonamaggio commented
@AgatheG are you ok with those changes?

2021-03-02 14:32 UTC, AgatheG approved these changes

2021-03-02 15:35 UTC, merged